spring:
  profiles:
    active: dev
  application:
    name: kaleido
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  resources:
    static-locations: classpath:/
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
logging:
  config: classpath:logback-spring.xml